### ISSUE TITLE
 Unsupported encoding command mac

### ISSUE THREAD

**Issue by albreax** [joniles/rtfparserkit#12]
I get  a "Unsupported encoding command mac" exception when I parse the clipboard rtf from Excel under OS X.

Example rtf:

{\rtf1\mac 
{\fonttbl{\f0\fnil Arial;}{\f1\fnil Arial;}{\f2\fnil Arial;}{\f3\fnil Arial;}{\f4\fnil Calibri;}{\f5\fnil Arial;}{\f6\fnil Arial;}{\f7\fnil Arial;}{\f8\fnil Arial;}{\f9\fnil Arial;}{\f10\fnil Arial;}{\f11\fnil Arial;}{\f12\fnil Arial Black;}{\f13\fnil Arial;}{\f14\fnil Arial;}{\f15\fnil Calibri Light;}{\f16\fnil Calibri;}{\f17\fnil Calibri;}{\f18\fnil Calibri;}{\f19\fnil Calibri;}{\f20\fnil Calibri;}{\f21\fnil Calibri;}{\f22\fnil Calibri;}{\f23\fnil Calibri;}{\f24\fnil Calibri;}{\f25\fnil Calibri;}{\f26\fnil Calibri;}{\f27\fnil Calibri;}{\f28\fnil Calibri;}{\f29\fnil Calibri;}{\f30\fnil Calibri;}{\f31\fnil Calibri;}{\f32\fnil Arial;}{\f33\fnil Arial;}{\f34\fnil Arial;}}
{\info{\id220}}\plain {\colortbl\red0\green0\blue0;\red255\green255\blue255;\red221\green8\blue6;\red31\green183\blue20;\red0\green0\blue212;\red252\green243\blue5;\red242\green8\blue132;\red0\green171\blue234;\red0\green0\blue0;\red255\green255\blue255;\red221\green8\blue6;\red31\green183\blue20;\red0\green0\blue212;\red252\green243\blue5;\red242\green8\blue132;\red0\green171\blue234;\red144\green0\blue0;\red0\green100\blue17;\red0\green0\blue144;\red144\green113\blue58;\red70\green0\blue165;\red0\green128\blue128;\red192\green192\blue192;\red128\green128\blue128;\red99\green170\blue254;\red221\green45\blue50;\red255\green245\blue140;\red78\green226\blue87;\red103\green17\blue255;\red254\green167\blue70;\red134\green83\blue87;\red162\green189\blue144;\red99\green170\blue254;\red221\green45\blue50;\red255\green245\blue140;\red78\green226\blue87;\red103\green17\blue255;\red254\green167\blue70;\red134\green83\blue87;\red162\green189\blue144;\red0\green204\blue255;\red204\green255\blue255;\red204\green255\blue204;\red255\green255\blue153;\red153\green204\blue255;\red255\green153\blue204;\red204\green153\blue255;\red255\green204\blue153;\red51\green102\blue255;\red51\green204\blue204;\red153\green204\blue0;\red255\green204\blue0;\red255\green153\blue0;\red255\green102\blue0;\red102\green102\blue153;\red150\green150\blue150;\red0\green51\blue102;\red51\green153\blue102;\red0\green51\blue0;\red51\green51\blue0;\red153\green51\blue0;\red153\green51\blue102;\red51\green51\blue153;\red51\green51\blue51;;\red255\green255\blue255;\red0\green0\blue0;\red221\green221\blue221;\red0\green0\blue0;\red255\green255\blue255;\red136\green136\blue136;\red164\green205\blue255;\red0\green0\blue0;\red128\green128\blue128;\red127\green127\blue127;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue153;\red0\green0\blue0;\red187\green191\blue202;\red56\green117\blue215;\red73\green142\blue234;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\red192\green192\blue192;\red150\green150\blue150;\red128\green128\blue128;\red102\green102\blue102;\red51\green51\blue51;\red95\green140\blue237;\red235\green94\blue96;\red141\green97\blue194;\red45\green150\blue57;\red191\green76\blue145;\red227\green130\blue34;\red55\green127\blue158;\red51\green102\blue153;\red128\green0\blue0;\red0\green128\blue0;\red0\green0\blue128;\red128\green128\blue0;\red128\green0\blue128;\red0\green128\blue128;\red0\green0\blue208;\red208\green215\blue229;}
\f5\fs16 \cf Last selected font is shown in menubar (see 18_01.jpg)}

**Comment by joniles** [comment]
I've fixed this and released a new version.

**Comment by albreax** [comment]
Awesome, thank you!
