### ISSUE TITLE
The whole project is broken because of missing Command.java

### ISSUE THREAD

**Issue by Nanocl** [joniles/rtfparserkit#14]
There's no com.rtfparserkit.rtf.Command class or interface. The complete rtf package seems to be missing.
Because of many classes reference Command, I'm not be able to compile the project (50 compilation errors at least).
So the whole API is not working for me.

**Comment by sebkirche** [comment]
[com.rtfparserkit.rtf.Command](https://github.com/joniles/rtfparserkit/blob/master/RTF%20Parser%20Kit/src/com/rtfparserkit/rtf/Command.java) exists though (it is an enum) and the project compiles.
How do you compile it ?

**Comment by Nanocl** [comment]
Hm, very curious. I checked out the master branch with eclipse and tried to compile it also with eclipse. There's no classpath to set. But the whole rtf package was missing.
Now I downloaded the Command.java and CommandType.java over the GitHub webinterface and completed the project and it works.

**Comment by joniles** [comment]
Closed as this appears to be working for the OP.
