### ISSUE TITLE
Java 9 compatibility

### ISSUE THREAD

**Issue by rarathore** [joniles/rtfparserkit#17]
Hi Team
	As you know Java9 release date is coming near (End of September 2017), So Please let me know whether you have any plan to incorporate Java 9 related changes in your libs,
Thanks a lot
Rajendra Rathore

**Comment by joniles** [comment]
Hi Rajendra, 

I'm not aware that any changes are required, the code should work fine as it is. Let me know if you find anything different!  

Jon

**Comment by rarathore** [comment]
I ran Jdeps on rtfparserkit.jar and found that com.rtfparserkit.utils.RtfDumpListener uses com.sun.xml.internal.txw2.output.IndentingXMLStreamWriter (JDK internal API (java.xml.bind)). So it is a warning but we need to fix that
Thanks a lot
Rajendra Rathore


Thanks and Regards,
Rajendra Rathore
9922701491

**Comment by joniles** [comment]
That class is only used to pretty-print XML in a demo class, you can probably ignore that.

**Comment by rarathore** [comment]
Ok thanks a lot Jon for your support.

Thanks and Regards,
Rajendra Rathore
9922701491
