### ISSUE TITLE
Incorrect encoding for current font

### ISSUE THREAD

**Issue by abLoftware** [joniles/rtfparserkit#23]
Believe this issue is related to https://github.com/joniles/rtfparserkit/issues/22

the encoding being used is being defaulted to font 0 rather then the currently set font (via \fN)
this appears to be an issue with the value of ParserState.currentFontExplicitlySet being "false"
in method StandardRtfParser.currentEncoding(), where if the value is false it sets 
the current encoding to whatever it is set for font 0

I've attached a unit test file and an rtf file,  
the unit test contains 2 tests, 1 that shows success if there is only 1 font, 
and 1 that fails if there are 2 fonts, and the second font is being used 
I've added ".txt" to the files since some extensions  are problematic for attachments

[testJapaneseJisEncoding_2Fonts.rtf.txt](https://github.com/joniles/rtfparserkit/files/4410143/testJapaneseJisEncoding_2Fonts.rtf.txt)

[TestBug2.java.txt](https://github.com/joniles/rtfparserkit/files/4410136/TestBug2.java.txt)

**Comment by joniles** [comment]
I _thin_ I've fixed the issue - new version available from Maven/GitHub now!

**Comment by abLoftware** [comment]
Looks good!
Thanks for the quick turnaround!!

Andre
